package com.mysimple.dao;

import java.io.Serializable;
import java.util.Date;

public class SysLogsRequest implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_logs_request.req_id
     *
     * @mbggenerated Fri Feb 02 11:05:59 CST 2018
     */
    private String reqId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_logs_request.api
     *
     * @mbggenerated Fri Feb 02 11:05:59 CST 2018
     */
    private String api;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_logs_request.return_code
     *
     * @mbggenerated Fri Feb 02 11:05:59 CST 2018
     */
    private Integer returnCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_logs_request.ip
     *
     * @mbggenerated Fri Feb 02 11:05:59 CST 2018
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_logs_request.run_time
     *
     * @mbggenerated Fri Feb 02 11:05:59 CST 2018
     */
    private Integer runTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_logs_request.request_len
     *
     * @mbggenerated Fri Feb 02 11:05:59 CST 2018
     */
    private Integer requestLen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_logs_request.response_len
     *
     * @mbggenerated Fri Feb 02 11:05:59 CST 2018
     */
    private Integer responseLen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_logs_request.create_time
     *
     * @mbggenerated Fri Feb 02 11:05:59 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_logs_request.user_id
     *
     * @mbggenerated Fri Feb 02 11:05:59 CST 2018
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_logs_request.app_key
     *
     * @mbggenerated Fri Feb 02 11:05:59 CST 2018
     */
    private String appKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_logs_request
     *
     * @mbggenerated Fri Feb 02 11:05:59 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_logs_request.req_id
     *
     * @return the value of sys_logs_request.req_id
     *
     * @mbggenerated Fri Feb 02 11:05:59 CST 2018
     */
    public String getReqId() {
        return reqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_logs_request.req_id
     *
     * @param reqId the value for sys_logs_request.req_id
     *
     * @mbggenerated Fri Feb 02 11:05:59 CST 2018
     */
    public void setReqId(String reqId) {
        this.reqId = reqId == null ? null : reqId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_logs_request.api
     *
     * @return the value of sys_logs_request.api
     *
     * @mbggenerated Fri Feb 02 11:05:59 CST 2018
     */
    public String getApi() {
        return api;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_logs_request.api
     *
     * @param api the value for sys_logs_request.api
     *
     * @mbggenerated Fri Feb 02 11:05:59 CST 2018
     */
    public void setApi(String api) {
        this.api = api == null ? null : api.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_logs_request.return_code
     *
     * @return the value of sys_logs_request.return_code
     *
     * @mbggenerated Fri Feb 02 11:05:59 CST 2018
     */
    public Integer getReturnCode() {
        return returnCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_logs_request.return_code
     *
     * @param returnCode the value for sys_logs_request.return_code
     *
     * @mbggenerated Fri Feb 02 11:05:59 CST 2018
     */
    public void setReturnCode(Integer returnCode) {
        this.returnCode = returnCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_logs_request.ip
     *
     * @return the value of sys_logs_request.ip
     *
     * @mbggenerated Fri Feb 02 11:05:59 CST 2018
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_logs_request.ip
     *
     * @param ip the value for sys_logs_request.ip
     *
     * @mbggenerated Fri Feb 02 11:05:59 CST 2018
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_logs_request.run_time
     *
     * @return the value of sys_logs_request.run_time
     *
     * @mbggenerated Fri Feb 02 11:05:59 CST 2018
     */
    public Integer getRunTime() {
        return runTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_logs_request.run_time
     *
     * @param runTime the value for sys_logs_request.run_time
     *
     * @mbggenerated Fri Feb 02 11:05:59 CST 2018
     */
    public void setRunTime(Integer runTime) {
        this.runTime = runTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_logs_request.request_len
     *
     * @return the value of sys_logs_request.request_len
     *
     * @mbggenerated Fri Feb 02 11:05:59 CST 2018
     */
    public Integer getRequestLen() {
        return requestLen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_logs_request.request_len
     *
     * @param requestLen the value for sys_logs_request.request_len
     *
     * @mbggenerated Fri Feb 02 11:05:59 CST 2018
     */
    public void setRequestLen(Integer requestLen) {
        this.requestLen = requestLen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_logs_request.response_len
     *
     * @return the value of sys_logs_request.response_len
     *
     * @mbggenerated Fri Feb 02 11:05:59 CST 2018
     */
    public Integer getResponseLen() {
        return responseLen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_logs_request.response_len
     *
     * @param responseLen the value for sys_logs_request.response_len
     *
     * @mbggenerated Fri Feb 02 11:05:59 CST 2018
     */
    public void setResponseLen(Integer responseLen) {
        this.responseLen = responseLen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_logs_request.create_time
     *
     * @return the value of sys_logs_request.create_time
     *
     * @mbggenerated Fri Feb 02 11:05:59 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_logs_request.create_time
     *
     * @param createTime the value for sys_logs_request.create_time
     *
     * @mbggenerated Fri Feb 02 11:05:59 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_logs_request.user_id
     *
     * @return the value of sys_logs_request.user_id
     *
     * @mbggenerated Fri Feb 02 11:05:59 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_logs_request.user_id
     *
     * @param userId the value for sys_logs_request.user_id
     *
     * @mbggenerated Fri Feb 02 11:05:59 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_logs_request.app_key
     *
     * @return the value of sys_logs_request.app_key
     *
     * @mbggenerated Fri Feb 02 11:05:59 CST 2018
     */
    public String getAppKey() {
        return appKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_logs_request.app_key
     *
     * @param appKey the value for sys_logs_request.app_key
     *
     * @mbggenerated Fri Feb 02 11:05:59 CST 2018
     */
    public void setAppKey(String appKey) {
        this.appKey = appKey == null ? null : appKey.trim();
    }
}