package com.mysimple.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.mysimple.dao.SysLogsRequest;
import com.mysimple.dao.SysLogsRequestExample;
import com.mysimple.dao.SysLogsRequestWithBLOBs;

public interface SysLogsRequestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_logs_request
     *
     * @mbggenerated Fri Feb 02 10:20:47 CST 2018
     */
    int countByExample(SysLogsRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_logs_request
     *
     * @mbggenerated Fri Feb 02 10:20:47 CST 2018
     */
    int deleteByExample(SysLogsRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_logs_request
     *
     * @mbggenerated Fri Feb 02 10:20:47 CST 2018
     */
    int deleteByPrimaryKey(String reqId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_logs_request
     *
     * @mbggenerated Fri Feb 02 10:20:47 CST 2018
     */
    int insert(SysLogsRequestWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_logs_request
     *
     * @mbggenerated Fri Feb 02 10:20:47 CST 2018
     */
    int insertSelective(SysLogsRequestWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_logs_request
     *
     * @mbggenerated Fri Feb 02 10:20:47 CST 2018
     */
    List<SysLogsRequestWithBLOBs> selectByExampleWithBLOBs(SysLogsRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_logs_request
     *
     * @mbggenerated Fri Feb 02 10:20:47 CST 2018
     */
    List<SysLogsRequest> selectByExample(SysLogsRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_logs_request
     *
     * @mbggenerated Fri Feb 02 10:20:47 CST 2018
     */
    SysLogsRequestWithBLOBs selectByPrimaryKey(String reqId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_logs_request
     *
     * @mbggenerated Fri Feb 02 10:20:47 CST 2018
     */
    int updateByExampleSelective(@Param("record") SysLogsRequestWithBLOBs record, @Param("example") SysLogsRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_logs_request
     *
     * @mbggenerated Fri Feb 02 10:20:47 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") SysLogsRequestWithBLOBs record, @Param("example") SysLogsRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_logs_request
     *
     * @mbggenerated Fri Feb 02 10:20:47 CST 2018
     */
    int updateByExample(@Param("record") SysLogsRequest record, @Param("example") SysLogsRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_logs_request
     *
     * @mbggenerated Fri Feb 02 10:20:47 CST 2018
     */
    int updateByPrimaryKeySelective(SysLogsRequestWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_logs_request
     *
     * @mbggenerated Fri Feb 02 10:20:47 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(SysLogsRequestWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_logs_request
     *
     * @mbggenerated Fri Feb 02 10:20:47 CST 2018
     */
    int updateByPrimaryKey(SysLogsRequest record);
}