package com.mysimple.dao.mapper;

import com.mysimple.dao.UserTest;
import com.mysimple.dao.UserTestExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserTestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test
     *
     * @mbggenerated Wed Jul 11 15:11:46 CST 2018
     */
    int countByExample(UserTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test
     *
     * @mbggenerated Wed Jul 11 15:11:46 CST 2018
     */
    int deleteByExample(UserTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test
     *
     * @mbggenerated Wed Jul 11 15:11:46 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test
     *
     * @mbggenerated Wed Jul 11 15:11:46 CST 2018
     */
    int insert(UserTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test
     *
     * @mbggenerated Wed Jul 11 15:11:46 CST 2018
     */
    int insertSelective(UserTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test
     *
     * @mbggenerated Wed Jul 11 15:11:46 CST 2018
     */
    List<UserTest> selectByExample(UserTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test
     *
     * @mbggenerated Wed Jul 11 15:11:46 CST 2018
     */
    UserTest selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test
     *
     * @mbggenerated Wed Jul 11 15:11:46 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserTest record, @Param("example") UserTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test
     *
     * @mbggenerated Wed Jul 11 15:11:46 CST 2018
     */
    int updateByExample(@Param("record") UserTest record, @Param("example") UserTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test
     *
     * @mbggenerated Wed Jul 11 15:11:46 CST 2018
     */
    int updateByPrimaryKeySelective(UserTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test
     *
     * @mbggenerated Wed Jul 11 15:11:46 CST 2018
     */
    int updateByPrimaryKey(UserTest record);
}